application: gae-pusher-test
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: main.py

- url: /trigger
  script: trigger.py

- url: /pusher/auth
  script: pusher_auth.py

- url: /pusher/presence_auth
  script: pusher_presence_auth.py  